export const RESERVED_USERNAMES = new Set([
  'admin',
  'administrator',
  'support',
  'help',
  'contact',
  'login',
  'logout',
  'signin',
  'signout',
  'signup',
  'register',
  'profile',
  'profiles',
  'community',
  'settings',
  'security',
  'system',
  'api',
  'root',
  'staff',
  'instructor',
  'student',
  'students',
  'user',
  'users',
  'username',
  'official',
  'zeitnah',
  'zeitnahacademy',
  'zeitnah_admin',
  'zeitnah_official',
  'dashboard',
  'courses',
  'course',
  'class',
  'classes',
  'chapter',
  'chapters',
  'my-learning',
  'my_learning',
  'my-points',
  'my_points',
  'active-sessions',
  'active_sessions',
  'audit-logs',
  'audit_logs',
  'session_diagnostics',
  'error_reports',
  'troubleshoot',
  'u',
  'verify',
  'auth',
  'notifications',
  'messages',
  'feed',
  'moderator',
  'superadmin',
  'null',
  'undefined',
  'bot',
  'moderation',
  'billing',
  'checkout',
  'payment',
  'terms',
  'privacy',
  'about',
  'faq',
  'home',
  'app',
]);

export function isReservedUsername(username: string): boolean {
  if (!username) return false;
  return RESERVED_USERNAMES.has(username.toLowerCase().trim());
}

// Configurable cooldown: User can change username once every 14 days
export const USERNAME_CHANGE_COOLDOWN_DAYS = 14;
export const USERNAME_CHANGE_COOLDOWN_MS =
  USERNAME_CHANGE_COOLDOWN_DAYS * 24 * 60 * 60 * 1000;
